INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (01, 'CERIMONIALISTA');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (02, 'PROFISSIONAIS DA BIOTECNOLOGIA E METROLOGIA ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (03, 'PROFISSIONAIS DA ELETROMECÂNICA ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (04, 'MATEMÁTICOS ESTATÍSTICOS E AFINS ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (05, 'PROFISSIONAIS DA INFORMÁTICA');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (06, 'ENGENHEIROS E ARQUITETOS');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (07, 'PROFISSIONAIS DA MEDICINA SAÚDE E AFINS');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (08, 'PROFISSIONAIS DA EDUCAÇÃO FÍSICA');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (09, 'PROFISSIONAIS DE SAÚDE EM PRATICAS INTEGRATIVAS E COMPLEMENTARES');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (10, 'PROFESSORES DE NÍVEL SUPERIOR NA EDUCAÇÃO INFANTIL E NO ENSINO FUNDAMENTAL');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (11, 'PROFESSORES DO ENSINO MÉDIO ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (12, 'PROFESSORES E INSTRUTORES DO ENSINO PROFISSIONAL');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (13, 'PROFESSORES DO ENSINO SUPERIOR');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (14, 'OUTROS PROFISSIONAIS DO ENSINO NÃO CLASSIFICADOS ANTERIORMENTE');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (15, 'ADVOGADOS PROCURADORES TABELIÃES E AFINS');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (16, 'CIENTISTAS SOCIAIS E PSICÓLOGOS');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (17, 'PROFISSIONAIS DE RELAÇÕES PÚBLICAS PUBLICIDADE MARKETING E COMERCIALIZAÇÃO');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (18, 'PROFISSIONAIS DA COMUNICAÇÃO E DA INFORMAÇÃO');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (19, 'PROFISSIONAIS DE ESPETÁCULOS E DAS ARTES');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (20, 'PROFISSIONAIS EM GASTRONOMIA E SERVIÇOS DE ALIMENTAÇÃO');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (21, 'TÉCNICOS MECATRÔNICOS E ELETROMECÂNICOS ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (22, 'TÉCNICO EM CIÊNCIAS FÍSICAS E QUÍMICAS');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (23, 'TÉCNICOS EM CONSTRUÇÃO CIVIL DE EDIFICAÇÕES E OBRAS DE INFRAESTRUTURA');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (24, 'TÉCNICOS EM ELETROELETRÔNICA E FOTÔNICA ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (25, 'TÉCNICOS EM METALMECÂNICA ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (26, 'TÉCNICOS EM INFORMÁTICA ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (27, 'DESENHISTAS TÉCNICOS E MODELISTAS ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (28, 'OUTROS TÉCNICOS DE NÍVEL MÉDIO DAS CIÊNCIAS FÍSICAS QUÍMICAS ENGENHARIA E AFINS ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (29, 'TÉCNICOS DA CIÊNCIA DA SAÚDE HUMANA ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (30, 'PROFESSORES DE NÍVEL MÉDIO NA EDUCAÇÃO INFANTIL NO ENSINO FUNDAMENTAL E NO PROFISSIONALIZANTE');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (31, 'PROFESSORES LEIGOS NO ENSINO FUNDAMENTAL E NOPROFISSIONALIZANTE ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (32, 'INSTRUTORES E PROFESSORES DE ESCOLAS LIVRES ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (33, 'INSPETORES DE ALUNOS E AFINS');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (34, 'TÉCNICOS DE NIVEL MÉDIO EM OPERAÇÕES COMERCIAIS ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (35, 'TÉCNICOS DE SERVIÇOS CULTURAIS');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (36, 'TÉCNICOS EM OPERAÇÃO DE EMISSORAS DE RÁDIO SISTEMAS DE TELEVISÃO E DE PRODUTORAS DE VÍDEO');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (37, 'TÉCNICOS EM OPERAÇÃO DE APARELHOS DE SONORIZAÇÃO CENOGRAFIA E PROJEÇÃO ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (38, 'DECORADORES E VITRINISTAS ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (39, 'ARTISTAS DE ARTES POPULARES E MODELOS ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (40, 'AUXILIARES DE SERVIÇOS DE BIBLIOTECA DOCUMENTAÇÃO E CORREIOS ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (41, 'TRABALHADORES DE INFORMAÇÕES AO PÚBLICO ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (42, 'ENTREVISTADORES RECENSEADORES E AFINS');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (43, 'TRABALHADORES DOS SERVIÇOS DE TRANSPORTE E TURISMO');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (44, 'TRABALHADORES DOS SERVIÇOS DOMÉSTICOS EM GERAL');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (45, 'TRABALHADORES DOS SERVIÇOS DE HOTELARIA E ALIMENTAÇÃO ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (46, 'TRABALHADORES NOS SERVIÇOS DE ADMINISTRAÇÃO CONSERVAÇÃO E MANUTENÇÃO DE EDIFÍCIOS E LOGRADOUROS');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (47, 'TRABALHADORES NOS SERVIÇOS DE EMBELEZAMENTO E CUIDADOS PESSOAIS ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (48, 'TRABALHADORES NOS SERVIÇOS DE PROTEÇÃO E SEGURANÇA');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (49, 'OUTROS TRABALHADORES DE SERVIÇOS DIVERSOS ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (50, 'VENDEDORES E DEMONSTRADORES ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (51, 'INSTALADORES DE PRODUTOS E ACESSÓRIOS ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (52, 'VENDEDORES A DOMICÍLIO AMBULANTES E EM BANCAS');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (53, 'TRABALHADORES DA IRRIGAÇÃO E DRENAGEM ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (54, 'TRABALHADORES DA CONSTRUÇÃO CIVIL E OBRAS PÚBLICAS');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (55, 'TRABALHADORES DE ACABAMENTO DE OBRAS');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (56, 'AJUDANTES DE OBRAS');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (57, 'TRABALHADORES DE USINAGEM DE METAIS E DE COMPÓSITOS ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (58, 'TRABALHADORES DE CONFORMAÇÃO DE METAIS E DE COMPÓSITOS');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (59, 'TRABALHADORES DE TRATAMENTO TÉRMICO E DE SUPERFÍCIES DE METAIS E DE COMPÓSITOS');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (60, 'TRABALHADORES DE MONTAGEM DE TUBULAÇÕES ESTRUTURAS METÁLICAS E DE COMPÓSITOS ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (61, 'MONTADORES DE MÁQUINAS E APARELHOS MECÂNICOS');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (62, 'MONTADORES E INSTALADORES DE EQUIPAMENTOS ELETROELETRÔNICOS EM GERAL');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (63, 'MONTADORES E AJUSTADORES DE INSTRUMENTOS DE PRECISÃO');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (64, 'MONTADORES E AJUSTADORES DE INSTRUMENTOS MUSICAIS ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (65, 'JOALHEIROS E OURIVES');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (66, 'VIDREIROS CERAMISTAS E AFINS ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (67, 'TRABALHADORES DAS INDUSTRIAS TÊXTEIS');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (68, 'TRABALHADORES DO TRATAMENTO DE COUROS E PELES ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (69, 'TRABALHADORES DA CONFECÇÃO DE ROUPAS');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (70, 'TRABALHADORES DA CONFECÇÃO DE CALÇADOS');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (71, 'TRABALHADORES DA CONFECÇÃO DE ARTEFATOS DE TECIDOS E COUROS ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (72, 'TRABALHADORES DA PRODUÇÃO GRÁFICA ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (73, 'TRABALHADORES ARTESANAIS DAS ATIVIDADES TÊXTEIS DO VESTUÁRIO E DAS ARTES GRÁFICAS');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (74, 'MARCENEIROS E AFINS ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (75, 'TRABALHADORES DE MONTAGEM DE MÓVEIS E ARTEFATOS DE MADEIRA');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (76, 'TRABALHADORES EM ACABAMENTO DE MADEIRA E DE MOBILIÁRIO');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (77, 'TRABALHADORES ARTESANAIS DA MADEIRA E DO MOBILIÁRIO ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (78, 'CONDUTORES DE VEÍCULOS E OPERADORES DE EQUIPAMENTOS DE ELEVAÇÃO E DE MOVIMENTAÇÃO DE CARGAS ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (79, 'TRABALHADORES DO ARTESANATO URBANO E RURAL');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (80, 'TRABALHADORES DE INSTALAÇÕES E EQUIPAMENTOS DE MATERIAL DE CONSTRUÇÃO CERÂMICA E VIDRO ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (81, 'TRABALHADORES ARTESANAIS NAAGROINDÚSTRIA NA INDÚSTRIA DE ALIMENTOS E DO FUMO ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (82, 'OPERADORES DE UTILIDADES');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (83, 'MECÂNICOS DE MANUTENÇÃO DE MÁQUINAS E EQUIPAMENTOS INDUSTRIAIS COMERCIAIS E RESIDENCIAIS ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (84, 'MECÂNICOS DE MANUTENÇÃO VEICULAR');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (85, 'REPARADORES DE INSTRUMENTOS E EQUIPAMENTOS DE PRECISÃO');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (86, 'OUTROS TRABALHADORES NA REPARAÇÃO E MANUTENÇÃO DE EQUIPAMENTOS');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (87, 'ELETRICISTAS ELETRÔNICOS DE MANUTENÇÃO INDUSTRIAL COMERCIAL E RESIDENCIAL');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (88, 'ELETRICISTAS ELETRÔNICOS DE MANUTENÇÃO VEICULAR ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (89, 'MANTENEDORES ELETROMECÂNICOS');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (90, 'OUTROS TRABALHADORES DA CONSERVAÇÃO E MANUTENÇÃO (EXCETO TRABALHADORES ELEMENTARES) ');
INSERT INTO tbl_categoria (id_categoria, categoria) VALUES (91, 'TRABALHADORES ELEMENTARES DA MANUTENÇÃO ');

#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (0101, 'Cerimonialista de Casamentos', 01);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (0201, 'Profissionais da metrologia', 02);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (0301, 'Engenheiros de controle e automação, engenheiros mecatrônicos e afins', 03);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (0401, 'Profissionais da matemática', 04);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (0402, 'Profissionais de estatística', 04);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (0501, 'Engenheiros em computação', 05);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (0502, 'Administradores de tecnologia da informação', 05);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (0503, 'Analistas de tecnologia da informação', 05);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (0601, 'Engenheiros ambientais e afins', 06);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (0602, 'Arquitetos e urbanistas', 06);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (0603, 'Engenheiros civis e afins', 06);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (0604, 'Engenheiros eletricistas, eletrônicos e afins', 06);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (0605, 'Engenheiros mecânicos e afins', 06);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (0606, 'Engenheiros de produção, qualidade, segurança e afins', 06);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (0701, 'Dentistas', 07);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (0702, 'Veterinários e zootecnistas', 07);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (0703, 'Enfermeiros', 07);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (0704, 'Fisioterapeutas', 07);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (0705, 'Nutricionistas', 07);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (0706, 'Fonoaudiólogos', 07);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (0707, 'Terapeutas ocupacionais, ortoptistas e psicomotricistas', 07);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (0801, 'Profissionais da educação física', 08);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (0901, 'Osteopatas e quiropraxistas', 09);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (0902, 'Profissionais das terapias criativas,equoterápicas e naturológicas', 09);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1001, 'Professores de nível superior na educação infantil', 10);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1002, 'Professores de nível superior do ensino fundamental (primeira a quarta séries)', 10);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1003, 'Professores de nível superior no ensino fundamental de quinta a oitava série', 10);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1101, 'Professores do ensino médio', 11);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1201, 'Professores do ensino profissional', 12);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1202, 'Instrutores de ensino profissional', 12);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1301, 'Professores de matemática, estatística e informática do ensino superior', 13);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1302, 'Professores de ciências físicas, químicas e afins do ensino superior', 13);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1303, 'Professores de arquitetura e urbanismo, engenharia, geofísica e geologia do ensino superior', 13);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1304, 'Professores de ciências biológicas e da saúde do ensino superior', 13);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1305, 'Professores na área de formação pedagógica do ensino superior', 13);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1306, 'Professores nas áreas de língua e literatura do ensino superior', 13);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1307, 'Professores de ciências humanas do ensino superior', 13);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1308, 'Professores de ciências econômicas, administrativas e contábeis do ensino superior', 13);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1309, 'Professores de artes do ensino superior', 13);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1401, 'Professores de educação especial', 14);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1402, 'Programadores, avaliadores e orientadores de ensino', 14);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1501, 'Advogados', 15);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1601, 'Profissionais em pesquisa e análise antropológica sociológica', 16);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1602, 'Economistas', 16);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1603, 'Profissionais em pesquisa e análise geográfica', 16);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1604, 'Psicólogos e psicanalistas', 16);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1605, 'Assistentes sociais e economistas domésticos', 16);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1701, 'Profissionais de publicidade', 17);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1801, 'Profissionais do jornalismo', 18);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1802, 'Profissionais da informação', 18);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1803, 'Arquivistas e museólogos', 18);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1804, 'Filólogos,tradutores ,intérpretes e afins', 18);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1805, 'Profissionais da escrita', 18);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1806, 'Editores', 18);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1807, 'Locutores, comentaristas e repórteres de mídias audiovisuais', 18);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1808, 'Fotógrafos profissionais', 18);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1809, 'Assistentes de direção (tv) e continuístas', 18);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1901, 'Produtores artísticos e culturais', 19);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1902, 'Diretores de espetáculos e afins', 19);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1903, 'Cenógrafos', 19);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1904, 'Artistas visuais,desenhistas industriais e conservadores-restauradores de bens culturais', 19);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1905, 'Atores', 19);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1906, 'Músicos compositores, arranjadores, regentes e musicólogos', 19);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1907, 'Músicos intérpretes', 19);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1908, 'Artistas da dança (exceto dança tradicional e popular)', 19);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (1909, 'Designer de interiores de nível superior', 19);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2001, 'Chefes de cozinha e afins', 20);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2101, 'Técnicos em mecatrônica', 21);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2102, 'Técnicos em eletromecânica', 21);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2201, 'Técnicos têxteis', 22);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2202, 'Coloristas', 22);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2301, 'Técnicos em construção civil (edificações, obras de infraestrutura)', 23);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2401, 'Técnicos em eletricidade e eletrotécnica', 24);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2402, 'Técnicos em eletrônica', 24);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2403, 'Técnicos em telecomunicações', 24);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2404, 'Técnicos em calibração e instrumentação', 24);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2501, 'Técnicos mecânicos na fabricação e montagem de máquinas, sistemas e instrumentos', 25);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2502, 'Técnicos mecânicos (ferramentas)', 25);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2503, 'Técnicos em mecânica veicular', 25);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2504, 'Técnicos mecânicos na manutenção de máquinas, sistemas e instrumentos', 25);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2601, 'Técnicos de desenvolvimento de sistemas e aplicações', 26);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2602, 'Técnicos em operação e monitoração de computadores', 26);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2701, 'Desenhistas técnicos, em geral', 27);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2702, 'Desenhistas técnicos da construção civil e arquitetura', 27);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2703, 'Desenhistas técnicos da mecânica', 27);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2704, 'Desenhistas técnicos em eletricidade, eletrônica, eletromecânica, calefação, ventilação e refrigeração', 27);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2705, 'Desenhistas técnicos de produtos e serviços diversos', 27);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2706, 'Desenhistas projetistas de construção civil e arquitetura', 27);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2707, 'Desenhistas projetistas da mecânica', 27);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2708, 'Desenhistas projetistas da eletrônica', 27);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2709, 'Desenhistas projetistas e modelistas de produtos e serviços diversos', 27);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2801, 'Técnicos do vestuário', 28);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2802, 'Técnicos do mobiliário e afins', 28);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2901, 'Tecnólogos e técnicos em terapias complementares e estéticas', 29);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2902, 'Técnicos e auxiliares de enfermagem', 29);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2903, 'Técnicos em óptica e optometria', 29);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2904, 'Técnicos de odontologia', 29);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2905, 'Técnicos em próteses ortopédicas', 29);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (2906, 'Técnicos de imobilizações ortopédicas', 29);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (3001, 'Professores de nível médio na educação infantil', 30);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (3002, 'Professores de nível médio no ensino fundamental', 30);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (3003, 'Professores de nível médio no ensino profissionalizante', 30);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (3101, 'Professores leigos no ensino fundamental', 31);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (3102, 'Professores práticos no ensino profissionalizante', 31);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (3201, 'Instrutores e professores de cursos livres', 32);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (3301, 'Inspetores de alunos e afins', 33);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (3401, 'Especialistas em promoção de produtos e vendas', 34);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (3402, 'Analistas de comércio exterior', 34);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (3403, 'Leiloeiros e avaliadores', 34);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (3404, 'Técnicos em serviços de turismo e organização de eventos', 34);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (3501, 'Técnicos em biblioteconomia', 35);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (3502, 'Técnicos em museologia e afins', 35);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (3503, 'Técnicos em artes gráficas', 35);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (3504, 'Recreadores', 35);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (3601, 'Técnicos de operação de registros sonoro/audiovisuais', 36);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (3701, 'Técnicos em áudio', 37);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (3702, 'Técnicos em cenografia', 37);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (3703, 'Técnicos em operação de aparelhos de projeção', 37);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (3704, 'Técnicos em montagem, edição e finalização de mídia audiovisual', 37);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (3801, 'Designers de interiores, de vitrines e visual merchandiser e afins (nível médio)', 38);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (3901, 'Dançarinos tradicionais e populares', 39);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (3902, 'Artistas de circo (circenses)', 39);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (3903, 'Apresentadores de eventos, programas e espetáculos', 39);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (3904, 'Modelos', 39);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (4001, 'Auxiliares de serviços de documentação, informação e pesquisa', 40);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (4002, 'Trabalhadores nos serviços de classificação e entregas de correspondências, encomendas e publicações', 40);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (4101, 'Recepcionistas', 41);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (4201, 'Entrevistadores e recenseadores', 42);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (4202, 'Aplicadores de provas e afins', 42);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (4301, 'Trabalhadores de segurança e atendimento aos usuários nos transportes', 43);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (4302, 'Guias de turismo', 43);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (4303, 'Condutores de turismo', 43);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (4401, 'Trabalhadores dos serviços domésticos em geral', 44);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (4501, 'Cozinheiros', 45);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (4502, 'Camareiros, roupeiros e afins', 45);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (4503, 'Trabalhadores no atendimento em estabelecimentos de serviços de alimentação, bebidas e hotelaria', 45);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (4504, 'Trabalhadores auxiliares nos serviços de alimentação', 45);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (4505, 'Churrasqueiros, pizzaiolos e sushimen', 45);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (4601, 'Trabalhadores nos serviços de coleta de resíduos, de limpeza e conservação de áreas públicas', 46);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (4701, 'Trabalhadores nos serviços de embelezamento e higiene', 47);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (4702, 'Cuidadores de crianças, jovens, adultos e idosos', 47);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (4703, 'Tintureiros, lavadeiros e afins, a máquina', 47);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (4704, 'Lavadores e passadores de roupa, a mão', 47);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (4801, 'Vigilantes e guardas de segurança', 48);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (4802, 'Porteiros, vigias e afins', 48);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (4901, 'Motociclistas e ciclistas de entregas rápidas', 49);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (4902, 'Trabalhadores da coleta e seleção de material reciclável', 49);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (4903, 'Trabalhadores de serviços veterinários, de higiene e estética de animais domésticos', 49);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (5001, 'Operadores do comércio em lojas e mercados', 50);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (5101, 'Instaladores de produtos e acessórios', 51);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (5201, 'Vendedores em domicílio', 52);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (5202, 'Vendedores em bancas, quiosques e barracas', 52);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (5301, 'Trabalhadores da irrigação e drenagem', 53);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (5401, 'Trabalhadores na operação de máquinas de terraplenagem e fundações', 54);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (5402, 'Trabalhadores de estruturas de alvenaria', 54);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (5403, 'Montadores de estruturas de concreto armado', 54);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (5404, 'Trabalhadores na operação de máquinas de concreto usinado', 54);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (5405, 'Trabalhadores de montagem de estruturas de madeira, metal e compósitos em obras civis', 54);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (5406, 'Trabalhadores de instalações elétricas', 54);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (5407, 'Aplicadores de materiais isolantes', 54);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (5501, 'Revestidores de concreto', 55);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (5502, 'Telhadores (revestimentos rígidos)', 55);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (5503, 'Vidraceiros (revestimentos rígidos)', 55);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (5504, 'Gesseiros', 55);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (5505, 'Aplicadores de revestimentos cerâmicos, pastilhas, pedras e madeiras', 55);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (5506, 'Pintores de obras e revestidores de interiores (revestimentos flexíveis)', 55);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (5601, 'Ajudantes de obras civis', 56);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (5701, 'Ferramenteiros e afins', 57);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (5702, 'Preparadores e operadores de máquinas-ferramenta convencionais', 57);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (5703, 'Afiadores e polidores de metais', 57);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (5801, 'Trabalhadores de moldagem de metais e de ligas metálicas', 58);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (5901, 'Trabalhadores da pintura de equipamentos, veículos, estruturas metálicas e de compósitos', 59);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (6001, 'Encanadores e instaladores de tubulações', 60);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (6101, 'Instaladores de equipamentos de refrigeração e ventilação', 61);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (6201, 'Montadores de equipamentos eletroeletrônicos', 62);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (6202, 'Montadores de aparelhos de telecomunicações', 62);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (6301, 'Mecânicos de instrumentos de precisão', 63);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (6401, 'Confeccionadores de instrumentos musicais', 64);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (6501, 'Joalheiros e lapidadores de gemas', 65);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (6502, 'Artesãos de metais preciosos e semi-preciosos', 65);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (6601, 'Sopradores, moldadores e modeladores de vidros e afins', 66);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (6602, 'Trabalhadores da transformação de vidros planos', 66);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (6603, 'Ceramistas (preparação e fabricação)', 66);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (6604, 'Vidreiros e ceramistas (arte e decoração)', 66);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (6701, 'Trabalhadores polivalentes das indústrias têxteis', 67);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (6702, 'Trabalhadores da classificação de fibras têxteis e lavagem de lã', 67);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (6703, 'Operadores da fiação', 67);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (6704, 'Operadores de tear e máquinas similares', 67);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (6705, 'Trabalhadores de acabamento, tingimento e estamparia das indústrias têxteis', 67);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (6801, 'Trabalhadores polivalentes do curtimento de couros e peles', 68);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (6802, 'Trabalhadores da preparação do curtimento de couros e peles', 68);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (6803, 'Trabalhadores do acabamento de couros e peles', 68);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (6901, 'Trabalhadores da preparação da confecção de roupas', 69);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (6902, 'Operadores de máquinas para costura de peças do vestuário', 69);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (6903, 'Operadores de máquinas para bordado e acabamento de roupas', 69);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (7001, 'Trabalhadores polivalentes da confecção de calçados', 70);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (7002, 'Trabalhadores da preparação da confecção de calçados', 70);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (7003, 'Trabalhadores de acabamento de calçados', 70);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (7101, 'Trabalhadores polivalentes da confecção de artefatos de tecidos e couros', 71);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (7102, 'Trabalhadores da preparação de artefatos de tecidos, couros e tapeçaria', 71);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (7103, 'Trabalhadores da confecção de artefatos de tecidos, couros e sintéticos', 71);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (7201, 'Trabalhadores da impressão gráfica', 72);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (7202, 'Trabalhadores de laboratório fotográfico e radiológico', 72);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (7301, 'Trabalhadores de tecelagem manual, tricô, crochê, rendas e afins', 73);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (7302, 'Trabalhadores artesanais da confecção de peças e tecidos', 73);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (7303, 'Trabalhadores artesanais da confecção de calçados e artefatos de couros e peles', 73);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (7304, 'Encadernadores e recuperadores de livros (pequenos lotes ou a unidade)', 73);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (7401, 'Marceneiros e afins', 74);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (7501, 'Montadores de móveis e artefatos de madeira', 75);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (7601, 'Trabalhadores de arte e  do acabamento em madeira do mobiliário', 76);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (7701, 'Confeccionadores de artefatos de madeira, móveis de vime e afins', 77);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (7801, 'Motoristas de veículos de pequeno e médio porte', 78);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (7802, 'Motoristas de veículos de cargas em geral', 78);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (7803, 'Condutores de animais e de veículos de tração animal e pedais', 78);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (7901, 'Jardineiro', 79);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (8001, 'Operadores de instalações e equipamentos de fabricação de materiais de construção', 80);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (8101, 'Padeiros, confeiteiros e afins', 81);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (8201, 'Operadores de instalações de captação, tratamento e distribuição de água', 82);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (8202, 'Operadores de instalações de captação e esgotos', 82);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (8203, 'Operadores de instalações de extração, processamento, envasamento e distribuição de gases', 82);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (8204, 'Operadores de instalações de refrigeração e ar-condicionado', 82);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (8301, 'Mecânicos de manutenção de bombas, motores, compressores e equipamentos de transmissão', 83);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (8302, 'Mecânicos de manutenção e instalação de aparelhos de  climatização e refrigeração', 83);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (8401, 'Mecânicos de manutenção aeronáutica', 84);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (8402, 'Mecânicos de manutenção de motores e equipamentos navais', 84);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (8403, 'Mecânicos de manutenção de veículos automotores', 84);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (8501, 'Técnicos em manutenção e reparação de instrumentos de medição e precisão', 85);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (8502, 'Restauradores de instrumentos musicais', 85);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (8503, 'Técnicos em manutenção e reparação de equipamentos biomédicos', 85);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (8504, 'Reparadores de equipamentos fotográficos', 85);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (8601, 'Lubrificadores', 86);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (8602, 'Trabalhadores de manutenção de roçadeiras, motoserras e similares', 86);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (8603, 'Mecânicos de manutenção de bicicletas e equipamentos esportivos e de ginástica', 86);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (8701, 'Eletricistas de manutenção eletroeletrônica', 87);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (8702, 'Instaladores e mantenedores de sistemas eletroeletrônicos de segurança', 87);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (8801, 'Eletricistas eletrônicos de manutenção veicular (aérea, terrestre e naval)', 88);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (8901, 'Instaladores e mantenedores eletromecânicos de elevadores, escadas e portas automáticas', 89);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (8902, 'Reparadores de aparelhos eletrodomésticos', 89);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (8903, 'Reparadores de equipamentos de escritório', 89);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (9001, 'Mantenedores de equipamentos de parques de diversões e similares', 90);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (9002, 'Reparadores de carrocerias de veículos', 90);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (9003, 'Mantenedores de edificações', 90);
INSERT INTO tbl_subcategoria (id_subcategoria, subcategoria, id_categoria) VALUES (9101, 'Trabalhadores elementares de serviços de manutenção veicular', 91);
