-- MySQL Script generated by MySQL Workbench
-- Thu Aug 29 23:40:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_daumhelp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_daumhelp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_daumhelp` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_daumhelp` ;

-- -----------------------------------------------------
-- Table `db_daumhelp`.`tbl_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_daumhelp`.`tbl_categoria` (
  `id_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(110) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_daumhelp`.`tbl_uf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_daumhelp`.`tbl_uf` (
  `id_uf` INT(11) NOT NULL AUTO_INCREMENT,
  `uf` VARCHAR(2) NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_uf`))
ENGINE = InnoDB
AUTO_INCREMENT = 54
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_daumhelp`.`tbl_microrregiao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_daumhelp`.`tbl_microrregiao` (
  `id_micro` INT(11) NOT NULL AUTO_INCREMENT,
  `micro` VARCHAR(100) NOT NULL,
  `id_uf` INT(11) NOT NULL,
  PRIMARY KEY (`id_micro`),
  INDEX `fk_uf_idx` (`id_uf` ASC) VISIBLE,
  CONSTRAINT `fk_uf`
    FOREIGN KEY (`id_uf`)
    REFERENCES `db_daumhelp`.`tbl_uf` (`id_uf`))
ENGINE = InnoDB
AUTO_INCREMENT = 53002
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_daumhelp`.`tbl_cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_daumhelp`.`tbl_cidade` (
  `id_cidade` INT(11) NOT NULL AUTO_INCREMENT,
  `cidade` VARCHAR(100) NOT NULL,
  `id_micro` INT(11) NOT NULL,
  PRIMARY KEY (`id_cidade`),
  INDEX `fk_micro_idx` (`id_micro` ASC) VISIBLE,
  CONSTRAINT `fk_micro`
    FOREIGN KEY (`id_micro`)
    REFERENCES `db_daumhelp`.`tbl_microrregiao` (`id_micro`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_daumhelp`.`tbl_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_daumhelp`.`tbl_endereco` (
  `id_endereco` INT(11) NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(200) NOT NULL,
  `cep` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `id_cidade` INT(11) NOT NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `fk_cidade_idx` (`id_cidade` ASC) VISIBLE,
  CONSTRAINT `fk_cidade`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `db_daumhelp`.`tbl_cidade` (`id_cidade`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_daumhelp`.`tbl_subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_daumhelp`.`tbl_subcategoria` (
  `id_subcategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `subcategoria` VARCHAR(120) NOT NULL,
  `id_categoria` INT(11) NOT NULL,
  PRIMARY KEY (`id_subcategoria`),
  INDEX `fk_categoria_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_sub`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `db_daumhelp`.`tbl_categoria` (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_daumhelp`.`tbl_profissional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_daumhelp`.`tbl_profissional` (
  `id_profissional` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(20) NULL DEFAULT NULL,
  `cpf` VARCHAR(20) NULL DEFAULT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `valor_hora` DOUBLE NOT NULL,
  `id_endereco` INT(11) NOT NULL,
  `id_subcategoria` INT(11) NOT NULL,
  PRIMARY KEY (`id_profissional`),
  INDEX `fk_endereco_idx` (`id_endereco` ASC) VISIBLE,
  INDEX `fk_subcategoria_idx` (`id_subcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_subcategoria`
    FOREIGN KEY (`id_subcategoria`)
    REFERENCES `db_daumhelp`.`tbl_subcategoria` (`id_subcategoria`),
  CONSTRAINT `fk_endereco`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `db_daumhelp`.`tbl_endereco` (`id_endereco`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
